name: CI
on: [push]
jobs:
  build:
    name: Build and test multilisten package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13.4'
      - run: go build ./multilisten
      - run: go test -cover ./multilisten
